//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLyKhachSan.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Booking
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Booking()
        {
            this.BookingServices = new HashSet<BookingService>();
        }
        [Key]
        public int idBooking { get; set; }
        public int totalMoney { get; set; }
        public string checkInDate { get; set; }
        public string checkOutDate { get; set; }
        public int status { get; set; }
        public bool isPayment { get; set; }
        public System.DateTime createdDate { get; set; }
        public int idRoom { get; set; }
        public int idUser { get; set; }
    
        public virtual Room Room { get; set; }
        public virtual User User { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BookingService> BookingServices { get; set; }
    }
}
