//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLyKhachSan.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Room
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Room()
        {
            this.RoomComments = new HashSet<RoomComment>();
        }
    
        public int idRoom { get; set; }
        public string name { get; set; }
        public string image { get; set; }
        public string description { get; set; }
        public int discount { get; set; }
        public int cost { get; set; }
        public int idType { get; set; }
        public int view { get; set; }
        public int numberChildren { get; set; }
        public int numberAdult { get; set; }
        public int idHotel { get; set; }
    
        public virtual Hotel Hotel { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RoomComment> RoomComments { get; set; }
        public virtual Type Type { get; set; }
    }
}
