//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLyKhachSan.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class RoomComment
    {
        public int idRoomComment { get; set; }
        public int idRoom { get; set; }
        public string text { get; set; }
        public int idUser { get; set; }
        public int star { get; set; }
        public System.DateTime createdDate { get; set; }
    
        public virtual Room Room { get; set; }
        public virtual User User { get; set; }
    }
}
